Fix JAR packaging so that the Kotlin-compiled main entry point can be found.
Before this change we were seeing:

```
kotlin_take-home % java -jar target/ki-takehome-kotlin-1.0-SNAPSHOT.jar
Error: Main method not found in class com.ki.LocalRunner, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application
```